site_name: JACoW - Running an IPAC
#site_url: https://docs-IPAC.JACoW.org
theme: material
repo_name: 'jacow-org/docs-IPAC'
repo_url: 'https://github.com/jacow-org/docs-IPAC'
nav:
  - Introduction: index.md
  - Glossary: glossary.md 
  - Organising Committees: committees.md
  - Delivery and Initial Setup - Admin:
    - Access to new event: InitialSetup/intro.md
    - Management area: 
      - Settings, Timetable, Protection: InitialSetup/mgmt_area_01.md
      - Organization: InitialSetup/mgmt_area_02.md
      - Workflows: InitialSetup/mgmt_area_03.md
      - Reports: InitialSetup/mgmt_area_04.md
      - Customization: InitialSetup/mgmt_area_05.md
  - Invited Oral Presentations:
    - Introduction: InvitedOrals/intro.md
    - Scientific Secretariat/Admin: 
      - Intial Setup: InvitedOrals/SSsetup.md
      - Submission of Proposals: InvitedOrals/SSsubmission.md
      - Post submission duties: InvitedOrals/SSpostsubmit.md
      - Call for Proposals for Invited Oral Presentations: InvitedOrals/SScall.md
      - Abstract Initial QA: InvitedOrals/SSinitialQA.md
    - OC/SPC/SAB:
      - Submission of Proposals for Invited Oral Presentations: InvitedOrals/SABsubmission.md

